server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/treasurehunting


mail:
  host: smtp.mailtrap.io
  port: 2525
  username: bd21da060388b3
  password: 1c5f38e2ea3548
  properties.mail.smtp:
    auth: true
    starttls.enable: true

logging:
  level:
    web: debug
    root: debug
    org:
      hibernate:
        type: debug
      springframework.web:
        type: debug
    hu.bme.aut.webshopbackend.type: debug


